# Generated by Django 5.0.6 on 2024-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_consultation_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=20, verbose_name='day'),
        ),
    ]
