# Generated by Django 5.0.6 on 2024-05-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_consultation_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='consultation',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], default='sun ', max_length=10),
        ),
    ]
