# Generated by Django 5.0.6 on 2024-05-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_consultation_day_of_week_consultation_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='day',
            new_name='date',
        ),
    ]
