# Generated by Django 5.0.6 on 2024-05-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_day_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation'),
        ),
    ]
