# Generated by Django 5.0.6 on 2024-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservation_capacity_of_members_reservation_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='capacity_of_members',
        ),
        migrations.AddField(
            model_name='reservation',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
