# Generated by Django 5.0.6 on 2024-05-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_member_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation_type',
            new_name='Consultation_type',
        ),
    ]
