# Generated by Django 5.0.6 on 2024-05-16 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_reservation_capacity_of_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_full',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='members',
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
