# Generated by Django 5.0.6 on 2024-05-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_consultation_is_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consultation')),
            ],
        ),
    ]
