# Generated by Django 5.0.6 on 2024-05-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_unavailableday_all_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableday',
            name='all_day',
        ),
        migrations.AddField(
            model_name='unavailableday',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
