# Generated by Django 5.0.6 on 2024-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_unavailableday_all_day_unavailableday_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableday',
            name='consultation',
        ),
        migrations.AddField(
            model_name='unavailableday',
            name='capacity',
            field=models.SmallIntegerField(null=True),
        ),
    ]
