# Generated by Django 5.0.6 on 2024-05-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_unavailableday_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='consultation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
