# Generated by Django 5.0.6 on 2024-06-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
